services:
  mysql:
    image: mysql:8

    container_name: banco_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: banco_digital
      MYSQL_USER: banco
      MYSQL_PASSWORD: 123456

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/banco.sql:/docker-entrypoint-initdb.d/01-banco.sql

volumes:
  mysql_data:
