services:
  postgres:
    image: postgres:17

    container_name: banco_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: banco_digital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/banco.sql:/docker-entrypoint-initdb.d/01-banco.sql

volumes:
  postgres_data:
